### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by EternalRat** [Garulf/twitchy#17]
Hello man, I did write my Client ID & Secret and here's the result...

Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/05/2022 00:38:28
Exception:
Twitchy Exception: 
Websites: https://github.com/Garulf/twitchy
Author: Garulf
Version: 6.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Twitchy|Traceback (most recent call last):
  File "C:\Users\Utilisateur\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\main.py", line 13, in <module>
    Twitchy()
  File "C:\Users\Utilisateur\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\plugin\twitchy.py", line 29, in __init__
    if not self.oauth_token or not self.client.validate_token():
  File "C:\Users\Utilisateur\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\lib\twitch\helix\api.py", line 75, in validate_token
    raise TwitchOAuthException("No OAuth token present.")
twitch.exceptions.TwitchOAuthException: No OAuth token present.
Exception ignored in: <function Launcher.__del__ at 0x0000021E55EF5A60>
Traceback (most recent call last):
  File "C:\Users\Utilisateur\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\lib\flox\launcher.py", line 16, in __del__
    self.run(debug)
  File "C:\Users\Utilisateur\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\lib\flox\launcher.py", line 22, in run
    if len(sys.argv) > 1:
TypeError: object of type 'NoneType' has no len()

 ---> System.IO.InvalidDataException: Twitchy|Traceback (most recent call last):
  File "C:\Users\Utilisateur\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\main.py", line 13, in <module>
    Twitchy()
  File "C:\Users\Utilisateur\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\plugin\twitchy.py", line 29, in __init__
    if not self.oauth_token or not self.client.validate_token():
  File "C:\Users\Utilisateur\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\lib\twitch\helix\api.py", line 75, in validate_token
    raise TwitchOAuthException("No OAuth token present.")
twitch.exceptions.TwitchOAuthException: No OAuth token present.
Exception ignored in: <function Launcher.__del__ at 0x0000021E55EF5A60>
Traceback (most recent call last):
  File "C:\Users\Utilisateur\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\lib\flox\launcher.py", line 16, in __del__
    self.run(debug)
  File "C:\Users\Utilisateur\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\lib\flox\launcher.py", line 22, in run
    if len(sys.argv) > 1:
TypeError: object of type 'NoneType' has no len()

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 626
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 627
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Hello @EternalRat,

Did you follow similar steps as I wrote here: 

https://github.com/Garulf/twitchy/issues/15#issuecomment-1237700013

You **MUST** close Flow Launchers settings after entering in you credentials. Flow only saves your settings when the window is closed.
