### ISSUE TITLE
TwitchAttributeException

### ISSUE THREAD

**Issue by SuperNon0** [Garulf/twitchy#18]
Please type any relevant information here

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\RIPno\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
  File "C:\Users\RIPno\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\plugin\twitchy.py", line 48, in _query
    self.query(query)
  File "C:\Users\RIPno\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\plugin\twitchy.py", line 75, in query
    _iterator = self.live_streams()
  File "C:\Users\RIPno\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\plugin\twitchy.py", line 103, in live_streams
    return self.client.get_streams(user_ids=following_ids)
  File "C:\Users\RIPno\AppData\Roaming\FlowLauncher\Plugins\Twitchy-6.0.0\lib\twitch\helix\api.py", line 109, in get_streams
    raise TwitchAttributeException("Maximum of 100 User IDs can be supplied")
twitch.exceptions.TwitchAttributeException: Maximum of 100 User IDs can be supplied

```
</p>
</details>

**Comment by Garulf** [comment]
Interesting error, I'll take a look.
